### ISSUE TITLE
Distribution Script (jquery.sparkline.js)

### ISSUE THREAD

**Issue by brunobelarmino** [gwatts/jquery.sparkline#109]
Can you available the distribution script (jquery.sparkline.js) on github? I use bower as dependency manager and he seeks scripts from github, which does not have the script in question.
Thanks

**Comment by RuslanZavacky** [comment]
+1

**Comment by rafanoronha** [comment]
:+1:

**Comment by jonasabreu** [comment]
+1

**Comment by willgm** [comment]
+1

**Comment by brunowego** [comment]
+1

**Comment by cthrax** [comment]
+1 but in the interim, https://github.com/smysnk/jquery.sparkline exists.

**Comment by filipegiusti** [comment]
Guys, this won't happen, the repo author said he is against it. The tools need to improve not the libraries needs to comply with tools that can't run a build process.

**Comment by cthrax** [comment]
Right, because RPM, .deb, .exe, .egg, .dll, etc, etc are all wrong in enforcing some sort of structure to a package. They all really should have adapted to every bit of source they are packaging.

**Comment by filipegiusti** [comment]
@cthrax the author is not against having bower.json or any other package meta info, he is against checking in the repo distribution packages because the dependency tool isn't capable of running a basic build or accepting deploy of a distribution package.

**Comment by cthrax** [comment]
I understand the problem just fine, even worked around it. The problem is the library does not provide any release artifacts and expects other tools to take care of that problem because a build script is provided. The maintainer is perfectly within their rights to take this stance, but it seems pretty darn silly to me. And I don't have to be happy about it.

**Comment by gwatts** [comment]
The release artifacts are linked from the web site.  No-one needs to build anything, unless they want to use the bleeding-edge, in which case you're expected to have the expertise to build it and not complain because the master branch is an unfinished release.

This git repo is for collaborative code development, not for release distribution.

Any fork of this repo can do whatever it likes, of course.

If the bower.json can reference the latest release on the web site, then that would be fine with me (ie. a pointer to http://omnipotent.net/jquery.sparkline/latest/jquery.sparkline.js), but I'm not checking in a compiled build into the source repo anytime soon to work around (imo) a design error with Bower.

**Comment by cthrax** [comment]
@gwatts as I said, you're prerogative, and as I pointed out earlier in the comment chain there is a fork that does accommodate bower, but standing on a high horse, due to a shortcoming (I'd not disagree with design flaw, but bower is still worlds better than having to download dependencies manually) of one of the more common and widely used dependency managers does not fix the problem (design flaw) nor increase the usefulness of a, what I deem, extremely well done library that is used by a large number of people. I'll continue using the fork that meets my needs, but I hope you will reconsider your stance in the future and provide a solution that is a little more accommodating.

Despite my unhappiness with this distribution issue, I'm extremely happy and thankful for the library and do appreciate all the work that's been put into it.

**Comment by gwatts** [comment]
I appreciate the problem with distribution management, but perhaps if everyone didn't capitulate to the design error, the error would be addressed and we'd all be a bit happier with the solution ;-)

Very pleased to hear that you're finding the library useful though.
